package org.bumble.demo.dao;

import org.bumble.demo.domain.MyUser;

public interface MyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    int insert(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    int insertSelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    MyUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    int updateByPrimaryKeySelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    int updateByPrimaryKey(MyUser record);
}