package org.bumble.demo.domain;

public class MyUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.id
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.username
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.password
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.mobile
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.nickname
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.realname
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.comment
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.id
     *
     * @return the value of my_user.id
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.id
     *
     * @param id the value for my_user.id
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.username
     *
     * @return the value of my_user.username
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.username
     *
     * @param username the value for my_user.username
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.password
     *
     * @return the value of my_user.password
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.password
     *
     * @param password the value for my_user.password
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.mobile
     *
     * @return the value of my_user.mobile
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.mobile
     *
     * @param mobile the value for my_user.mobile
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.nickname
     *
     * @return the value of my_user.nickname
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.nickname
     *
     * @param nickname the value for my_user.nickname
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.realname
     *
     * @return the value of my_user.realname
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.realname
     *
     * @param realname the value for my_user.realname
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.comment
     *
     * @return the value of my_user.comment
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.comment
     *
     * @param comment the value for my_user.comment
     *
     * @mbggenerated Thu Jun 07 13:30:55 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}